---
- hosts: localhost
  connection: local
  tasks:
  - name: Create S3 test bucket.
    local_action:
      module: aws_s3
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      bucket: "{{bucket_name}}"
      mode: create
  - name: Set userid tag to bucket
    local_action:
      module: s3_bucket
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      name: "{{bucket_name}}"
      encryption: AES256
      tags:
        Uid: "{{user_id}}"