---
- hosts: localhost
  connection: local
  tasks:
  - name: Simple GET operation
    local_action:
      module: aws_s3
      aws_access_key: "{{access_key}}"
      aws_secret_key: "{{secret_key}}"
      bucket: "{{bucket_name}}"
      object: "{{object_name}}" # can give path also of virtual directories
      dest: "{{file_name}}" # Path where file to be downloaded with name
      mode: get
      version: "{{version_name}}" #will work only if versioning is enabled
