---
- hosts: localhost
  connection: local
  tasks:
  - name: List objects
    local_action:
      module: aws_s3
      aws_access_key: "{{access_key}}"
      aws_secret_key: "{{secret_key}}"
      bucket: "{{bucket_name}}"
      mode: list
    register: result
  - name: List objects
    debug:
      msg: "{{ result['s3_keys'] }}"
      
