# Generated by Django 2.2.3 on 2019-07-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
