# Generated by Django 2.2.3 on 2019-07-05 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_userdata_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_url_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='https://www.google.com', max_length=200)),
                ('subscribers', models.CharField(default='', max_length=800)),
                ('status', models.IntegerField(default=200)),
                ('access', models.CharField(default='', max_length=10)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Userdata')),
            ],
        ),
    ]
