# Generated by Django 2.2.3 on 2019-07-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_user_url_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
