# Generated by Django 2.2.3 on 2019-07-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20190705_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_url_info',
            name='cron',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_url_info',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
