# Generated by Django 2.2.3 on 2019-07-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20190705_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_name',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
