# Generated by Django 2.2.3 on 2019-10-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20190709_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(default='qwe', max_length=32),
        ),
        migrations.DeleteModel(
            name='User_url_info',
        ),
    ]
